### PR TITLE
Fix @metric_scope for generator and async generator functions

### PR DESCRIPTION
**Pull request by acradu**
*Issue #, if available:*
* #112 

*Description of changes:*
This change updates `@metric_scope` to iterate through the wrapped generator, allowing metric collection on each iteration

### CODE REVIEW

**Comment by fernandoaguilar** [comment]
anyone plan on merging this in? this fixes the no current running event loop error for us, we will have to fork the repo otherwise if this is not merged in. @acradu

**Review by tonytan4ever — APPROVED** [review]

**Review by fernandoaguilar — APPROVED** [review]

**Review by gordonpn — APPROVED** [review]

**Review by johnjang — APPROVED** [review]
LGTM

**Comment by drduhe** [comment]
Can you do a latest release with this change?

**Comment by julius-yang** [comment]
> Can you do a latest release with this change?

Seconded, we are currently using a fork with this change but it would be nice to point to this repo again.

**Comment by hussam789** [comment]
## PR Code Suggestions ✨



<table><thead><tr><td><strong>Category</strong></td><td align=left><strong>Suggestion&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></td><td align=center><strong>Impact</strong></td></tr><tbody><tr><td rowspan=3>Possible issue</td>
<td>



<details><summary>Fix async generator exception handling</summary>

___


**The exception handling for async generators is incorrect. <code>StopAsyncIteration</code> <br>should be caught instead of <code>StopIteration</code> for async generators. The current code <br>will not properly handle the end of the async generator.**

[aws_embedded_metrics/metric_scope/__init__.py [28-37]](https://github.com/awslabs/aws-embedded-metrics-python/pull/113/files#diff-386e5fc7b7f871a40df2c7a91d9662db7e72234f1eda096ab7576c637fd7876eR28-R37)

```diff
 try:
     fn_gen = fn(*args, **kwargs)
     while True:
         result = await fn_gen.__anext__()
         await logger.flush()
         yield result
 except Exception as ex:
     await logger.flush()
-    if not isinstance(ex, StopIteration):
+    if not isinstance(ex, StopAsyncIteration):
         raise
```

- [ ] **Apply this suggestion** 

<details><summary>Suggestion importance[1-10]: 8</summary>

__

Why: The suggestion correctly identifies that the async generator’s termination should be signaled by StopAsyncIteration rather than StopIteration, which is a subtle but important bug fix for async generators.


</details></details></td><td align=center>Medium

</td></tr><tr><td>



<details><summary>Fix event loop handling</summary>

___


**Using <code>asyncio.run()</code> in the synchronous wrapper can cause issues if called from a <br>context where an event loop is already running. This can lead to "RuntimeError: <br>This event loop is already running". Consider using a more compatible approach <br>for running the async flush operation.**

[aws_embedded_metrics/metric_scope/__init__.py [84-85]](https://github.com/awslabs/aws-embedded-metrics-python/pull/113/files#diff-386e5fc7b7f871a40df2c7a91d9662db7e72234f1eda096ab7576c637fd7876eR84-R85)

```diff
 finally:
-    asyncio.run(logger.flush())
+    try:
+        loop = asyncio.get_event_loop()
+        if loop.is_running():
+            # Create a future to run in the existing loop
+            future = asyncio.run_coroutine_threadsafe(logger.flush(), loop)
+            future.result()
+        else:
+            loop.run_until_complete(logger.flush())
+    except RuntimeError:
+        # No event loop in this thread, create a new one
+        loop = asyncio.new_event_loop()
+        loop.run_until_complete(logger.flush())
+        loop.close()
```

- [ ] **Apply this suggestion** 

<details><summary>Suggestion importance[1-10]: 6</summary>

__

Why: The suggestion addresses a potential RuntimeError when asyncio.run() is invoked in an environment with an already running event loop, but the proposed solution may add unnecessary complexity in contexts where it might not be needed.


</details></details></td><td align=center>Low

</td></tr><tr><td>



<details><summary>Improve event loop handling</summary>

___


**Using <code>asyncio.run()</code> inside a generator function can cause issues as it creates <br>and tears down a new event loop on each iteration. This is inefficient and can <br>lead to problems if there are other async operations in progress. Consider using <br>a more efficient approach for flushing the logger.**

[aws_embedded_metrics/metric_scope/__init__.py [48-57]](https://github.com/awslabs/aws-embedded-metrics-python/pull/113/files#diff-386e5fc7b7f871a40df2c7a91d9662db7e72234f1eda096ab7576c637fd7876eR48-R57)

```diff
 try:
     fn_gen = fn(*args, **kwargs)
+    loop = asyncio.new_event_loop()
     while True:
         result = next(fn_gen)
-        asyncio.run(logger.flush())
+        loop.run_until_complete(logger.flush())
         yield result
 except Exception as ex:
-    asyncio.run(logger.flush())
+    loop.run_until_complete(logger.flush())
+    loop.close()
     if not isinstance(ex, StopIteration):
         raise
```

- [ ] **Apply this suggestion** 

<details><summary>Suggestion importance[1-10]: 5</summary>

__

Why: While the suggestion calls out potential inefficiencies in repeatedly calling asyncio.run(), the approach of creating a new event loop may introduce unforeseen complexity and is not clearly superior to the existing implementation.


</details></details></td><td align=center>Low

</td></tr>
<tr><td align="center" colspan="2">

- [ ] More 

</td><td></td></tr></tbody></table>

**Pull request merged**
