### PR TITLE
Migrate from IMDSv1 to IMDSv2

### PR DESCRIPTION
**Pull request by Himtanaya**
*Issue #, if available:*
N/A

*Description of changes:*
IMDSv2 uses session authentication to retrieve EC2 instance metadata.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by waifa** [comment]
Looks like code build for your latest commit is failing?

**Comment by Himtanaya** [comment]
Build for the last commit passed. Can you refresh maybe you are not seeing the latest commit or it's possible GitHub is not updating build status. 

image

**Comment by Himtanaya** [comment]
> Can we remove those two "Fix flake8 issues" commits? They don't seem to be adding anything substantial/relevant to this PR. If they are needed you can squash them into one commit to keep our commits clean.

I am going to squash and merge, so there will be only one commit.

**Review by evanuk — APPROVED** [review]
👍

**Comment by hussam789** [comment]
## PR Code Suggestions ✨



<table><thead><tr><td><strong>Category</strong></td><td align=left><strong>Suggestion&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </strong></td><td align=center><strong>Impact</strong></td></tr><tbody><tr><td rowspan=2>Possible issue</td>
<td>



<details><summary>Check HTTP response status</summary>

___


**The <code>fetchString</code> function should check the HTTP status code before returning the <br>response text. If the status code indicates an error, the function should raise <br>an exception to properly handle failure cases.**

[aws_embedded_metrics/environment/ec2_environment.py [48-52]](https://github.com/awslabs/aws-embedded-metrics-python/pull/78/files#diff-ea0943a8dd95c131dc682d1761afa6166340d86e908484e2cd00f6524ef73365R48-R52)

```diff
 async def fetchString(
     session: aiohttp.ClientSession, method: str, url: str, headers: Dict[str, str]
 ) -> str:
     async with session.request(method, url, timeout=2, headers=headers) as response:
+        response.raise_for_status()
         return await response.text()
```

- [ ] **Apply this suggestion** 

<details><summary>Suggestion importance[1-10]: 8</summary>

__

Why: This suggestion enhances error handling in the fetchString function by ensuring that HTTP error responses raise exceptions before processing the body, which improves robustness without altering the core functionality.


</details></details></td><td align=center>Medium

</td></tr><tr><td>



<details><summary>Validate HTTP response status</summary>

___


**Similar to the <code>fetchString</code> function, <code>fetchJSON</code> should check the HTTP status code <br>before processing the response to ensure proper error handling.**

[aws_embedded_metrics/environment/ec2_environment.py [38-45]](https://github.com/awslabs/aws-embedded-metrics-python/pull/78/files#diff-ea0943a8dd95c131dc682d1761afa6166340d86e908484e2cd00f6524ef73365R38-R45)

```diff
 async def fetchJSON(
     session: aiohttp.ClientSession, method: str, url: str, headers: Dict[str, str],
 ) -> Dict[str, Any]:
     async with session.request(method, url, timeout=2, headers=headers) as response:
+        response.raise_for_status()
         # content_type=None prevents validation of the HTTP Content-Type header
         # The EC2 metadata endpoint uses text/plain instead of application/json
         # https://github.com/aio-libs/aiohttp/blob/7f777333a4ec0043ddf2e8d67146a626089773d9/aiohttp/web_request.py#L582-L585
         return cast(Dict[str, Any], await response.json(content_type=None))
```

- [ ] **Apply this suggestion** 

<details><summary>Suggestion importance[1-10]: 8</summary>

__

Why: By adding a status check using response.raise_for_status() in fetchJSON, this suggestion ensures that any HTTP errors are caught early, aligning error handling consistently with similar improvements and enhancing overall reliability.


</details></details></td><td align=center>Medium

</td></tr>
<tr><td align="center" colspan="2">

- [ ] More 

</td><td></td></tr></tbody></table>

**Pull request merged**
